events { worker_connections 1024; }
http {
    upstream backend {
        server searchsurge-master:8080;
        server searchsurge-slave:8080;
    }
    upstream master_only {
        server searchsurge-master:8080;
    }
    server {
        listen 80;
        location /top { proxy_pass http://backend; }
        location /stoplist { proxy_pass http://master_only; }
        location /health { proxy_pass http://backend; }
        location /metrics { proxy_pass http://backend:9091; }
    }
}