global:
  scrape_interval: 10s
  evaluation_interval: 10s
  external_labels:
    cluster: searchsurge
    environment: prod

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: searchsurge-master
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["searchsurge-master:9091"]
        labels:
          role: master

  - job_name: searchsurge-slave
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["searchsurge-slave:9091"]
        labels:
          role: slave

  - job_name: nginx
    static_configs:
      - targets: ["searchsurge-nginx:80"]
    metrics_path: /stub_status
    scheme: http