global:
  scrape_interval: 10s
  evaluation_interval: 10s
  external_labels:
    cluster: searchsurge
    environment: prod

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: searchsurge-master
    static_configs:
      - targets: ["searchsurge-master:9091"]
    labels:
      role: master
    metrics_path: /metrics
    scheme: http

  - job_name: searchsurge-slaves
    dns_sd_configs:
      - names: ["tasks.searchsurge-slave"]
        type: A
        port: 9091
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: [__meta_dns_name]
        target_label: slave_name

  - job_name: nginx
    static_configs:
      - targets: ["searchsurge-nginx:80"]
    metrics_path: /stub_status
    scheme: http