// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/api.proto

package surgpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TrendService_StreamTop_FullMethodName      = "/surge.v1.TrendService/StreamTop"
	TrendService_GetTop_FullMethodName         = "/surge.v1.TrendService/GetTop"
	TrendService_UpdateStoplist_FullMethodName = "/surge.v1.TrendService/UpdateStoplist"
)

// TrendServiceClient is the client API for TrendService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrendServiceClient interface {
	StreamTop(ctx context.Context, in *StreamTopRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TopSnapshot], error)
	GetTop(ctx context.Context, in *GetTopRequest, opts ...grpc.CallOption) (*GetTopResponse, error)
	UpdateStoplist(ctx context.Context, in *StoplistRequest, opts ...grpc.CallOption) (*StoplistResponse, error)
}

type trendServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrendServiceClient(cc grpc.ClientConnInterface) TrendServiceClient {
	return &trendServiceClient{cc}
}

func (c *trendServiceClient) StreamTop(ctx context.Context, in *StreamTopRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TopSnapshot], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TrendService_ServiceDesc.Streams[0], TrendService_StreamTop_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamTopRequest, TopSnapshot]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TrendService_StreamTopClient = grpc.ServerStreamingClient[TopSnapshot]

func (c *trendServiceClient) GetTop(ctx context.Context, in *GetTopRequest, opts ...grpc.CallOption) (*GetTopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTopResponse)
	err := c.cc.Invoke(ctx, TrendService_GetTop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trendServiceClient) UpdateStoplist(ctx context.Context, in *StoplistRequest, opts ...grpc.CallOption) (*StoplistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoplistResponse)
	err := c.cc.Invoke(ctx, TrendService_UpdateStoplist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrendServiceServer is the server API for TrendService service.
// All implementations must embed UnimplementedTrendServiceServer
// for forward compatibility.
type TrendServiceServer interface {
	StreamTop(*StreamTopRequest, grpc.ServerStreamingServer[TopSnapshot]) error
	GetTop(context.Context, *GetTopRequest) (*GetTopResponse, error)
	UpdateStoplist(context.Context, *StoplistRequest) (*StoplistResponse, error)
	mustEmbedUnimplementedTrendServiceServer()
}

// UnimplementedTrendServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrendServiceServer struct{}

func (UnimplementedTrendServiceServer) StreamTop(*StreamTopRequest, grpc.ServerStreamingServer[TopSnapshot]) error {
	return status.Error(codes.Unimplemented, "method StreamTop not implemented")
}
func (UnimplementedTrendServiceServer) GetTop(context.Context, *GetTopRequest) (*GetTopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTop not implemented")
}
func (UnimplementedTrendServiceServer) UpdateStoplist(context.Context, *StoplistRequest) (*StoplistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateStoplist not implemented")
}
func (UnimplementedTrendServiceServer) mustEmbedUnimplementedTrendServiceServer() {}
func (UnimplementedTrendServiceServer) testEmbeddedByValue()                      {}

// UnsafeTrendServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrendServiceServer will
// result in compilation errors.
type UnsafeTrendServiceServer interface {
	mustEmbedUnimplementedTrendServiceServer()
}

func RegisterTrendServiceServer(s grpc.ServiceRegistrar, srv TrendServiceServer) {
	// If the following call panics, it indicates UnimplementedTrendServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TrendService_ServiceDesc, srv)
}

func _TrendService_StreamTop_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamTopRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TrendServiceServer).StreamTop(m, &grpc.GenericServerStream[StreamTopRequest, TopSnapshot]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TrendService_StreamTopServer = grpc.ServerStreamingServer[TopSnapshot]

func _TrendService_GetTop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrendServiceServer).GetTop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrendService_GetTop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrendServiceServer).GetTop(ctx, req.(*GetTopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrendService_UpdateStoplist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoplistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrendServiceServer).UpdateStoplist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrendService_UpdateStoplist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrendServiceServer).UpdateStoplist(ctx, req.(*StoplistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TrendService_ServiceDesc is the grpc.ServiceDesc for TrendService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrendService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "surge.v1.TrendService",
	HandlerType: (*TrendServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTop",
			Handler:    _TrendService_GetTop_Handler,
		},
		{
			MethodName: "UpdateStoplist",
			Handler:    _TrendService_UpdateStoplist_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTop",
			Handler:       _TrendService_StreamTop_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/api.proto",
}
